name = "scouting-report"
main = "src/worker.js"
compatibility_date = "2026-09-08"

[assets]
directory = "./public"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "scouting-report"
database_id = "fdd6de15-1298-4629-81bd-90bcef1ee08b"
